### ISSUE TITLE
Function error in dev-branch

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/pacman-mirrors#99]
@fhdk: please recheck our dev-branch. Seems we have a regression:

```
(47/50) Aktualisiere pacman-mirrors-dev            [######################] 100%
Traceback (most recent call last):
  File "/usr/bin/pacman-mirrors", line 55, in <module>
    pm.run()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 552, in run
    self.command_line_parse()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 205, in command_line_parse
    if args.sync:
AttributeError: 'Namespace' object has no attribute 'sync'
```

**Stable** branches are fine.

**Comment by philmmanjaro** [comment]
Please also check **v4.1** series, as some checks failed ...

**Comment by fhdk** [comment]
I removed the -y --sync arg - I realized it was confusing and also it is not a pacman clone but a mirrorlist helper and the -u --update should not have been there at all.

I must keep the purpose of pacman-mirrors as it is - mirrorlist generator - not a nurse :)

This regression is fixed with https://github.com/manjaro/pacman-mirrors/commit/8939ed64a26f9e1face25f2c83f4012c2547021a

**Comment by fhdk** [comment]
I have checked - I fixed another bug in 4.1-series.

**Status**
**For 4.1.3-stable**
* Fixed comparison of mirror files. The comparison of the newly downloaded and the existing mirror file failed due to a bad comparison by me. Found that the builtin function `filecmp` would do a much better job.

**For 4.2.0-dev**
* Same as 4.1.2 fix
* Same as 4.1.3 fix
* regression bug fix (described above)
* fixed some sorting and output problems related to protocol selection - partly relating to the 4.1.2 fix
